import Navigation from '@/components/navigation'
import './globals.css'
import QueryWrapper from './queryWrapper'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <QueryWrapper>
          <Navigation />
          {children}
        </QueryWrapper>
      </body>
    </html>
  )
}
